version: 2.1

references:
  workspace: &workspace
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace

executors:
  node:
    docker:
      - image: cimg/node:lts
    working_directory: *workspace

jobs:
  build:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - persist_to_workspace:
          root: *workspace
          paths:
            - "*"
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  test:
    executor: node
    steps:
      - *attach_workspace
      - run: npm run test:ci

  deploy:
    executor: node
    steps:
      - *attach_workspace
      - run: mkdir .vercel/
      - run: echo "{\"projectId\":\"${NOW_PROJECT_ID}\",\"orgId\":\"${NOW_ORG_ID}\"}" > .vercel/project.json
      - run: npm run --silent vercel -- -t $ZEIT_NOW_TOKEN
      - run: npm run --silent vercel -- -t $ZEIT_NOW_TOKEN --prod

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          context: zeit-now
          requires:
            - test
          filters:
            branches:
              only:
                - master
